sudo: required
services:
  - docker

language: node_js
node_js:
  - "6.1"

install:
  - cd app && npm install

script: npm run test

after_success:
  - cd ..
  - sh travis_deploy.sh

cache:
  directories:
    - app/node_modules