sudo: required
services:
  - docker

language: node_js
node_js:
  - "6.1"

install:
  - cd app && npm install

after_success:
  - chmod +x build/travis_deploy.sh
  - build/travis_deploy.sh

cache:
  directories:
    - app/node_modules