version: '2'

services:
  build-service:
    build: 
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - ".:/usr/src"
      - "/var/run/docker.sock:/var/run/docker.sock"
    env_file:
      - .build.env
    privileged: true